### ISSUE TITLE
ENHANCEMENT REQ: Learned Abilities

### ISSUE THREAD

**Issue by rhodan412** [corporategoth/rotationmaster#13]
Could you implement, into your addon, the ability to read if a certain ability is learned?

Currently for this to "work," I need to set the level of my character, in the conditions, to list the same level that the ability is learned, but this doesn't take into account if I'm grinding mobs/finishing quests between the time of hitting that level and visiting the trainer to actually learn the spell.

The second part to this feature request would be the ability to enter in spell name on a toon that doesn't yet have the ability.  For example, on a lower level priest, being able to create a rotation starting with Shadowform when the spell/talent is not yet learned on THAT character.  If I use a high enough character (that has that spell/talent) I can input it and then export the information to my lower level alt.

**Comment by corporategoth** [comment]
There is already a condition of 'Spell is Available' - it should cover that case (among others).
That said, Rotation Master is already smart enough to check IsSpellKnown when evaluating a rotation step, so if you don't know it, the condition should be skipped, regardless of the conditions you use.

re: spells you don't know.  You could use 'Any Spell' instead of just 'Spell' (any spell lets you select any spell in the game).  There  are 3 kinds of spell actions/conditions.  "Spell" which specifically looks for spells in your spell book, "Pet Spell" which does what it says on the tin (though it will only show pet spells for pets you have summoned since last UI reload, this is a WoW restriction), and "Any Spell", which takes off the guard rails completely and lets you select any spell at all.  Even for a different class, or that an NPC would cast.

The any spell list might take some time to populate, though you can always just put in the spell ID (look it up on wowhead) and it will figure it out.

Does that answer everything in this ticket?  I believe that everything you are asking for is already part of the addon.

**Comment by rhodan412** [comment]
Yes that answered this ticket fully.  I did have to update to the current version (v1.4.1a) to get the any spell and apply the fix that was listed in #11.

Love the add-on and thank you for your help on this :)
