### ISSUE TITLE
Allow multiple spells to have the same priority

### ISSUE THREAD

**Issue by david-driscoll** [corporategoth/rotationmaster#2]
This is an odd one.  Playing in the wrath beta as my paladin. The issue I'm running into is there no way to create a rotation that allows me to easily switch a judgement spell off my bar one of the three judgement abilities to be on my bars.

Basically paladins get three different judgements ([Justice](https://www.wowhead.com/wotlk/spell=53407/judgement-of-justice), [Light](https://www.wowhead.com/wotlk/spell=20271/judgement-of-light) and [Wisdom](https://www.wowhead.com/wotlk/spell=53408/judgement-of-wisdom)) and you might switch up what judgement your doing periodically.  They all share the same cooldown, and act as if you judged your current seal, the only difference is the effect on the mob you hit.  So what I'd like is the ability for RM to just highlight any of my judgement abilities, instead of just one, if that makes sense.

**Comment by corporategoth** [comment]
This is ideally what the "Cooldowns" are for.
They are not necessarily part of the rotation (though you could add an 'in combat' condition) - and they will highlight when necessary regardless of what's going on with the rest of your rotation.  And any or all cooldowns could be highlighted at once.

**Comment by david-driscoll** [comment]
Yeah, problem is judgement is part of the rotation, so using a cooldown doesn't quiet fit with that. it has a priority above one thing or another, but just the actual spell you have to cast can change based on comp.

**Comment by corporategoth** [comment]
I am implementing this slightly different than what you are suggesting.
I am adding a 'No Action' option to the rotation.  SO, what you could do, is setup cooldowns for Justice, Light & Wisdom (highlighting only if none of them are up)
And then in your rotation, add a 'No Action' if none of the judgements are up.  This could also be achieved currently by adding a spell or item you don't have on your bars too.  But the change will make this more explicit.

This way, your rotation would essentially stop until you have a judgement up, and the cooldowns would be inactive if any of the judgements are up.

This is a lot simpler to implement and understand with how Rotation Master is written right now.  It is written so that one cooldown or one rotation step only highlights one thing (it could highlight multiple buttons if you for some reason have multiple copies of the same spell on your bars - but each step only highlights one spell).

It would be a big change to make steps highlight multiple spells and would make the addon more confusing to use.

**Comment by corporategoth** [comment]
Should be able to achieve this using the mechanism I mentioned above in 1.4.0 beta1
